#! /bin/bash

awk -F ',' '
  /filename/ \
  {

    for (i=3; i<=NF; ++i) 
      print $i

  }

'  $1 \
|

sed 's/D:\\/\/run\/media\/shady\/Media\// ; s/\\/\//g' |

nohup mpv --playlist=- > /dev/null 2>&1 &
