#!/bin/bash

SESSIONNAME="khedma"
KHEDMA_PATH=~/development/laravel/khedma/khedma_laravel/
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
 then
    tmux new-session -s $SESSIONNAME -c $KHEDMA_PATH -n sail -d
    tmux send-keys -t $SESSIONNAME:0 "sail up" C-m

    tmux new-window -t $SESSIONNAME -c $KHEDMA_PATH -n vim
    tmux send-keys -t $SESSIONNAME:1 "vim ." C-m "g."
fi

tmux attach -t $SESSIONNAME
