#!/bin/bash

SESSIONNAME="problem-solving"
PROBLEMS_PATH=~/development/php
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
 then
    tmux new-session -s $SESSIONNAME -c $PROBLEMS_PATH -n vim -d
    tmux send-keys -t $SESSIONNAME:0 "vim ." C-m

    tmux new-window -t $SESSIONNAME -c $PROBLEMS_PATH -n run -d
    tmux send-keys -t $SESSIONNAME:1 "c" C-m run
fi

tmux attach -t $SESSIONNAME
