#!/bin/bash

SESSIONNAME="cv"
CV_PATH=~/development/My-CV
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
 then
    tmux new-session -s $SESSIONNAME -c $CV_PATH -n vim -d
    tmux send-keys -t $SESSIONNAME:0 "vim ." C-m run

    tmux new-window -t $SESSIONNAME -c $CV_PATH -n build
    tmux send-keys -t $SESSIONNAME:1 "c" C-m "resume"
fi

tmux attach -t $SESSIONNAME
